import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Homepage | UpLeveled, template: %s | UpLeveled' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div>Board & Card Game Arena</div>
        </header>
        <nav>
          <ul>
            <li>
              <Link href="/allmeetups">All Meetups</Link>
            </li>
            <li>
              <Link href="/addnewmeetup">Add New Meetup</Link>
            </li>
            <li>
              <Link href="/cart">Cart</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
